# Generated by Django 4.0.4 on 2022-05-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nacimiento', models.DateTimeField()),
                ('parentesco', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('europeo', models.BooleanField()),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
